### ISSUE TITLE
subscription remember with createDependency error

### ISSUE THREAD

**Issue by katywings** [alojs/alo#24]
Test the following order:

- create subscription
- add stores
- create Dependencies
- add member
- remember

```
alo.full.js:7048 Uncaught (in promise) TypeError: Cannot read property 'stores' of undefined
    at http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:8240:43
    at arrayEach$1 (http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:1025:9)
    at Util.forEach (http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:4359:10)
    at http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:8239:11
    at callHanler (http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:7436:16)
    at tryCatcher (http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:7154:32)
    at http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:7292:38
    at flush (http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:7196:17)
    at MutationObserver.Observer.observe.characterData (http://ext.office.glarotech.ch/~lutzkatj/katjashop_master/lib/alo/alo.full.js:7581:4)
```

```js
Subscription.prototype._publish = function (state) {
  var self = this;
  if (self._muted === false) {
    self._muted = true;
    var promise = u.Promise.resolve().then(function () {
      return self._callEvent('beforePublish', state)
    }).then(function (runPublish) {
      self._muted = false;
      if (runPublish !== false) {
        var state = self.getData();
        var promises = [];
        u.forEach(self.getMember(false), function (member) {
          **promises.push(member._call(state.stores, state.computed));**
        });
        return u.Promise.all(promises)
      } else {
```

**Comment by katywings** [comment]
State was undefined in this execution order :), added an if check for state.
